//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnt.ObjectBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cnt.ObjectBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object builder has no strategies..
        /// </summary>
        internal static string BuilderHasNoStrategies {
            get {
                return ResourceManager.GetString("BuilderHasNoStrategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} / {2} :: {3}.
        /// </summary>
        internal static string BuilderStrategyTraceBuildUp {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} :: {2}.
        /// </summary>
        internal static string BuilderStrategyTraceTearDown {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Finished BuildUp on {0} with ID {1}.
        /// </summary>
        internal static string BuildUpFinished {
            get {
                return ResourceManager.GetString("BuildUpFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Starting BuildUp on {0} with ID {1}.
        /// </summary>
        internal static string BuildUpStarting {
            get {
                return ResourceManager.GetString("BuildUpStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enumeration value..
        /// </summary>
        internal static string InvalidEnumerationValue {
            get {
                return ResourceManager.GetString("InvalidEnumerationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the given key is already present in the dictionary..
        /// </summary>
        internal static string KeyAlreadyPresentInDictionary {
            get {
                return ResourceManager.GetString("KeyAlreadyPresentInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Finished TearDown on {0}.
        /// </summary>
        internal static string TearDownFinished {
            get {
                return ResourceManager.GetString("TearDownFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Starting TearDown on {0}.
        /// </summary>
        internal static string TearDownStarting {
            get {
                return ResourceManager.GetString("TearDownStarting", resourceCulture);
            }
        }
    }
}
